version: '3.9'

services:
  events-service:
    build:
      context: ./services/events-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ticketing_events
      SPRING_DATASOURCE_USERNAME: events_user
      SPRING_DATASOURCE_PASSWORD: 123456789
    depends_on:
      db:
        condition: service_healthy

  orders-service:
    build:
      context: ./services/orders-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://orders-db:5432/ticketing_orders
      SPRING_DATASOURCE_USERNAME: orders_user
      SPRING_DATASOURCE_PASSWORD: 123456789
      EVENTS_SERVICE_BASE_URL: http://events-service:8080
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_ORDERS_TOPIC: orders.events
      KAFKA_PAYMENTS_TOPIC: payments.events
    depends_on:
      orders-db:
        condition: service_healthy
      events-service:
        condition: service_started
      kafka:
        condition: service_started

  payment-service:
    build:
      context: ./services/payment-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://payment-db:5432/ticketing_payment
      SPRING_DATASOURCE_USERNAME: payment_user
      SPRING_DATASOURCE_PASSWORD: 123456789
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_ORDERS_TOPIC: orders.events
      KAFKA_PAYMENTS_TOPIC: payments.events
    depends_on:
      payment-db:
        condition: service_healthy

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      zookeeper:
        condition: service_started
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ticketing_events
      POSTGRES_USER: events_user
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
      interval: 10s
      timeout: 5s
      retries: 5

  orders-db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ticketing_orders
      POSTGRES_USER: orders_user
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5435:5432"
    volumes:
      - orders-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\"" ]
      interval: 10s
      timeout: 5s
      retries: 5

  payment-db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ticketing_payment
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5436:5432"
    volumes:
      - payment-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\"" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  orders-db-data:
  payment-db-data:
  zookeeper-data:
  kafka-data: