version: '3.9'

services:
  events-service:
    build:
      context: ./services/events-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ticketing_events
      SPRING_DATASOURCE_USERNAME: events_user
      SPRING_DATASOURCE_PASSWORD: 123456789
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ticketing_events
      POSTGRES_USER: events_user
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data: