version: '3.9'

services:
  eureka-server:
    build:
      context: ./services/eureka-server
      dockerfile: Dockerfile
    environment:
      EUREKA_INSTANCE_HOSTNAME: eureka-server
    ports:
      - "8761:8761"

  gateway-service:
    build:
      context: ./services/gateway-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      eureka-server:
        condition: service_started

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/ticketing_auth
      SPRING_DATASOURCE_USERNAME: auth_user
      SPRING_DATASOURCE_PASSWORD: 123456789
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
    depends_on:
      auth-db:
        condition: service_healthy
      eureka-server:
        condition: service_started

  events-service:
    build:
      context: ./services/events-service
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ticketing_events
      SPRING_DATASOURCE_USERNAME: events_user
      SPRING_DATASOURCE_PASSWORD: 123456789
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      db:
        condition: service_healthy
      eureka-server:
        condition: service_started
      redis:
        condition: service_healthy

  notifications-service:
    build:
      context: ./services/notifications-service
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://notifications-db:5432/ticketing_notifications
      SPRING_DATASOURCE_USERNAME: notifications_user
      SPRING_DATASOURCE_PASSWORD: 123456789
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_ORDERS_TOPIC: orders.events
      KAFKA_PAYMENTS_TOPIC: payments.events
      KAFKA_EVENTS_TOPIC: events.events
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
    depends_on:
      notifications-db:
        condition: service_healthy
      kafka:
        condition: service_started
      eureka-server:
        condition: service_started

  orders-service:
    build:
      context: ./services/orders-service
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://orders-db:5432/ticketing_orders
      SPRING_DATASOURCE_USERNAME: orders_user
      SPRING_DATASOURCE_PASSWORD: 123456789
      EVENTS_SERVICE_BASE_URL: http://events-service:8080
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_ORDERS_TOPIC: orders.events
      KAFKA_PAYMENTS_TOPIC: payments.events
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
    depends_on:
      orders-db:
        condition: service_healthy
      events-service:
        condition: service_started
      kafka:
        condition: service_started
      eureka-server:
        condition: service_started

  payment-service:
    build:
      context: ./services/payment-service
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://payment-db:5432/ticketing_payment
      SPRING_DATASOURCE_USERNAME: payment_user
      SPRING_DATASOURCE_PASSWORD: 123456789
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_ORDERS_TOPIC: orders.events
      KAFKA_PAYMENTS_TOPIC: payments.events
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
    depends_on:
      payment-db:
        condition: service_healthy
      eureka-server:
        condition: service_started

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      zookeeper:
        condition: service_started
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ticketing_events
      POSTGRES_USER: events_user
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
      interval: 10s
      timeout: 5s
      retries: 5

  notifications-db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ticketing_notifications
      POSTGRES_USER: notifications_user
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5438:5432"
    volumes:
      - notifications-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\"" ]
      interval: 10s
      timeout: 5s
      retries: 5

  orders-db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ticketing_orders
      POSTGRES_USER: orders_user
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5435:5432"
    volumes:
      - orders-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\"" ]
      interval: 10s
      timeout: 5s
      retries: 5

  payment-db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ticketing_payment
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5436:5432"
    volumes:
      - payment-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\"" ]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ticketing_auth
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5437:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\"" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  orders-db-data:
  payment-db-data:
  auth-db-data:
  notifications-db-data:
  zookeeper-data:
  kafka-data: